language: go
go:
- 1.12.x
cache:
- yarn
- directories:
  - node_modules
  - "$GOPATH/pkg"
script:
- make setup-go
- make lint
- make test
- git describe --tags HEAD
- make xbuild
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "WnAT5+Rv/YudzxS2euEvHx8Yunk8vAtoiWtLC4xhE2SJDHx2QyxOsFKPuky2voicV31vc4EdL727th1lRC2S7ZlkEg7GtGzBlM9cn96yjK92xKOsluIDUPP/SMmzHHIJTHhiwGfZsWoNykMzI6O2Gz6MsD0tkY6yB6/3DpwJb1bIYHK0IhHmB4gb0q6CcDBBZCQVFeZ2udht1flG77T7KXwFeqGv+iRtiLfHuXTlWGeM3OuMt2QVRuK4gK5y6cdfi0FZgFB1ysnklRBw3r/o6MPlFxvT5YiiKV9+7/TtUE80VFOIfJbJ5JFkcIPV9p4NM1mhGhlTJ1nAG3z/XkuMJtIRndl/XTU+oow2GeoXydifb+stZe8RRus4yHHUHeF8bCQgwa1HS7b1ani02APKWQkSmhOo0k4T+6IhGORXtsMZ0MhVWK/5g63JjhVdaI913uVewvA7lDwBzo6HjdNRP0ur4kKDfM9O3BvdeYt9u/Yfl34yaUo2OA2yOzSYQpsF/nPrHP946qgltzfDmJnhEx5GIXihkmriEq9n85W9ODHz73lXBmCbtxbG79l0+VcSqtplmIleQb1SsnP2S7f3XhRQ48PL84mTdxEkaWWnbptACR5T+Ex9gK2FxmQAxyh9ok5Eh3wqxzHb9TXJcuuBovGm7whF0+qUC2EdN7Akdmg="
  file_glob: true
  file: build/*
  on:
    repo: motemen/prchecklist
    condition: $TRAVIS_GO_VERSION =~ ^1\.12
    tags: true

