language: go
go:
- 1.12.x
cache:
- yarn
- directories:
  - node_modules
  - "$GOPATH/pkg"
script:
- make setup-go
- make lint
- make test
- git describe --tags HEAD
- make xbuild
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: gF6Y7pQ2RBMf9qNAqPuy9Xd1ZzJFtOeweVwW8Ax4n65e03nYZuk3XZIW49m4sjKGgZr06aMYqWSgdQ74h+Z8bi6ocDiBBBsXTgeTLZHYYDqybfqpwKkJVJXlNunQpJH4lLyxAt39xbRpPSXhJ2JqnrSajM+MWJ8yr5mrVmDrHwETcQkPEKlBiF2vF1/ubMbZQNcyTU5dii5DYWIjA5hKj+hC1YSEvqh68QtgCjDY38BxItD9e7D+X3LdyelgA3HvIjk3m9ne9DhVfCrmmUYmA0AXD1HZ1agtInWYHGxhMwzHP/yGq9l9eFEuZ/BZIb2S04Pf6uFV2Lap+wIgzMX6clAcVa7fE68WQVDemUgKNV2gdATBS58L8OabeLWNfcc76h6RtmeJ5LMW0wce3CkgJ98eB7nGJDVXgr++2+gLZehr0EuNPQ4loOjcOBUFvq+9ospqRXQC5OpRyAl3piorHx62scj3ABaBqhmW8HcP+bvdUgFUB6TP2Ec6QDP6BIbcjSlqu3V4BRFfaZSKKXvvTA5NuqglLDA9fHNnpHNVBoZRHtfs5/2B+UZDo72QyzhTKNFX2RJ9j2OtYXLmuBevY9v1jWiyCdO5v3V0dmLGr73fw7PiLaHjn3KWgGb1q0B0000wIH0cyy/h4GTsAasaNN89ZqHgwdDw6ebIe8gwYKA=
  file_glob: true
  file: build/*
  on:
    repo: motemen/prchecklist
    condition: $TRAVIS_GO_VERSION =~ ^1\.12
    tags: true

