name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - uses: actions/setup-node@v1.1.0

    - uses: actions/checkout@v2

    - run: |
        make setup

    - run: |
        make lint

    - run: |
        make test

    - run: |
        make build
